kumuluzee:
  name: bikecatalogservice
  version: 1.0.0
  env:
    name: dev
  server:
    http:
      port: 8082
  datasources:
  - jndi-name: jdbc/bikecatalogservice
    connection-url: jdbc:postgresql://localhost:5432/cityBikeShare
    username: postgres
    password: admin
    max-pool-size: 20

  discovery:
    etcd:
      hosts: http://localhost:2379

  config:
    etcd:
      hosts: http://localhost:2379

  health:
    checks:
      data-source-health-check:
        jndi-name: jdbc/bikecatalogservice
      http-health-check:
      - connection-url: https://github.com/CityBikeShare/BikeCatalogService
#      - connection-url: https://nonvalidurl.com
  metrics:
    web-instrumentation:
    - name: metrics-endpoint
      url-pattern: /sources/*
      status-codes: "200, 400, 404, 500"
    servlet:
      enabled: true